[supervisord]
nodaemon=true
user=root

[program:aria2]
command=aria2c --conf-path=/var/lib/aria2/aria2.conf --enable-rpc --rpc-listen-all=true --rpc-listen-port=6800 --dir=/downloads --save-session=/var/lib/aria2/aria2.session --input-file=/var/lib/aria2/aria2.session --save-session-interval=60 --force-save=true --rpc-allow-origin-all=true
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
